import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import fs from 'fs';

/**
 * Generates a medical report PDF.
 * @param {Object} userData - user info
 * @param {Object} predictionData - result from ML model
 * @param {string} predictionType - 'Heart', 'Diabetes', etc.
 * @returns {Promise<Uint8Array>} - The PDF bytes
 */
export const generatePDFReport = async (userData, predictionData, predictionType) => {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage();
    const { width, height } = page.getSize();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const fontSize = 12;
    let y = height - 50;

    // Header
    page.drawText('Multi-Predict Medical Report', {
        x: 50,
        y: y,
        size: 20,
        font: boldFont,
        color: rgb(0, 0.53, 0.71),
    });
    y -= 40;

    // User Info
    page.drawText(`Patient Name: ${userData.fullName}`, { x: 50, y, size: fontSize, font });
    y -= 20;
    page.drawText(`Email: ${userData.email}`, { x: 50, y, size: fontSize, font });
    y -= 20;
    page.drawText(`Date: ${new Date().toLocaleDateString()}`, { x: 50, y, size: fontSize, font });
    y -= 40;

    // Prediction Section
    page.drawText(`Analysis Type: ${predictionType} Prediction`, { x: 50, y, size: 16, font: boldFont });
    y -= 30;

    // Status/Result
    const status = predictionData.label || (predictionData.prediction === 1 ? "Positive (Risk Detected)" : "Negative (Healthy)");
    const color = (predictionData.prediction === 1 || predictionData.label === "Malignant") ? rgb(0.8, 0, 0) : rgb(0, 0.6, 0);

    page.drawText(`Result: ${status}`, {
        x: 50,
        y,
        size: 14,
        font: boldFont,
        color: color
    });
    y -= 25;

    // Confidence
    if (predictionData.confidence !== undefined) {
        page.drawText(`Confidence Score: ${(predictionData.confidence * 100).toFixed(2)}%`, { x: 50, y, size: fontSize, font });
        y -= 40;
    }

    // Disclaimer
    page.drawText('Disclaimer:', { x: 50, y, size: 10, font: boldFont });
    y -= 15;
    page.drawText('This report is generated by an AI system and should not be used as a substitute', { x: 50, y, size: 10, font });
    y -= 15;
    page.drawText('for professional medical advice. Please consult a doctor for clinical diagnosis.', { x: 50, y, size: 10, font });

    const pdfBytes = await pdfDoc.save();
    return pdfBytes;
};
